Listed explicitly the requirements.
The use of setup.py generated an error at doc generation, due to 
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-req-build-zlo7j1fs/spyrit/fht/fht/C_fht.template.c'